const menuList = [
    {
        title:'首页',
        key:'/admin/home'
    },
    {
        title:'UI',
        key:'/admin/ui',
        children:[
            {
                title:'按钮',
                key:'/admin/ui/button'
            },
            {
                title:'输入框',
                key:'/admin/ui/inputs'
            },
            {
                title:'表单',
                key:'/admin/ui/form'
            },
            {
                title:'表格',
                key:'/admin/ui/tables'
            },
        ]
    }
];
export default menuList;